### ISSUE TITLE
`map': undefined method `hosts' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by displague** [compumike/hairpin-proxy#1]
```
2020-10-27 19:32:22 +0000: Fetching...
/app/src/main.rb:9:in `map': undefined method `hosts' for nil:NilClass (NoMethodError)
	from /app/src/main.rb:9:in `ingress_hosts'
	from /app/src/main.rb:31:in `block in main'
	from /app/src/main.rb:28:in `loop'
	from /app/src/main.rb:28:in `main'
	from /app/src/main.rb:50:in `<main>'
```

https://github.com/compumike/hairpin-proxy/blob/1d13489ec6ba97d492910717a218f623370808b0/hairpin-proxy-controller/src/main.rb#L9

I do have two extensions/v1beta1 ingresses in different namespaces in k8s 1.16:

```yaml
spec:
  tls:
  - hosts:
    - foo
```

**Comment by compumike** [comment]
Hi @displague thanks for reporting this! Looks like it was dying when there was any non-SSL Ingress present in the cluster -- oops.

I believe I've fixed this in ab191f643e3d72b1e1842d8944c3da173f935a67 and published a new tagged release v0.1.1. Can you try this again?

1. Run `kubectl apply -f https://raw.githubusercontent.com/compumike/hairpin-proxy/master/deploy.yml` 
2. Verify that the new `0.1.1` version images (not the old `0.1`) come up with `kubectl get pods -n hairpin-proxy -o jsonpath="{.items[*].spec.containers[*].image}"`)

Please let me know if the new version works or not. Closing the issue as I believe it's fixed, but happy to reopen if not.

**Comment by displague** [comment]
@compumike That worked! Cert-manager was able to run the self-check and my cert applied.

**Comment by compumike** [comment]
@displague Excellent :smile:
