### ISSUE TITLE
CoreDNS configmap not updated

### ISSUE THREAD

**Issue by marek-obuchowicz** [compumike/hairpin-proxy#11]
I've noticed in controller output proper values:
```I, [2021-03-26T21:57:47.994768 #1]  INFO -- : Polling all Ingress resources and CoreDNS configuration...
I, [2021-03-26T21:57:48.058982 #1]  INFO -- : Corefile has changed! New contents:
import /etc/coredns/extra-configs/*Corefile
      .:53 {
    rewrite name alertmanager.stl.xxx.dev hairpin-proxy.hairpin-proxy.svc.cluster.local # Added by hairpin-proxy
    rewrite name grafana.stl.xxx.dev hairpin-proxy.hairpin-proxy.svc.cluster.local # Added by hairpin-proxy
    rewrite name prometheus.stl.xxx.dev hairpin-proxy.hairpin-proxy.svc.cluster.local # Added by hairpin-proxy
          errors
          health
          kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
          }
          prometheus :9153
          forward . /etc/resolv.conf
          cache 30
          loop
          reload
          loadbalance
      }
Sending updated ConfigMap to Kubernetes API server...
```

However, the coredns ConfigMap does not get updated and it holds only original values:
```
kubectl get configmap -n kube-system coredns -o=jsonpath='{.data.Corefile}'

      import /etc/coredns/extra-configs/*Corefile
      .:53 {
          errors
          health
          kubernetes cluster.local in-addr.arpa ip6.arpa {
             pods insecure
             fallthrough in-addr.arpa ip6.arpa
          }
          prometheus :9153
          forward . /etc/resolv.conf
          cache 30
          loop
          reload
          loadbalance
      }
```
controller container does not throw any errors, it just tells it updates configMap and this does not happen...
I'm running k8s version `1.20.4`

**Comment by compumike** [comment]
That's very strange. I wonder if there's an admission controller blocking this for some reason. Have you tried editing the ConfigMap directly `kubectl edit configmap -n kube-system coredns` and seeing if the cluster accepts edits made that way?

**Comment by marek-obuchowicz** [comment]
I see that indeed, there's something specific on this cluster (it's a managed cluster from local provider). I can edit configmap, but any change is instantly overwritten by original contents (this can be seen by `kns kube-system get configmaps coredns -w` - after each edit, another change happens on this configmap instantly). I suspected it could have something to do with k8s api versions and lack of support for 1.20.x, but it seems to be provider-specific issue.
