### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by vitobotta** [compumike/hairpin-proxy#5]
Like the subject says I just wanted to thank you for this brilliant solution to this annoying problem! I am starting to use Linode's managed Kubernetes and they don't have yet an annotation for the load balancer service that forces traffic through the load balancer with proxy protocol enabled, like other services do.

This solution of yours works perfectly and cert manager was able to issue a test certificate.

Thanks!

**Comment by compumike** [comment]
You're welcome @vitobotta . I appreciate the note. I may leave this issue open for a while so more people see it :joy:

On a wider note, my guess is that it would be healthy for the open source community at large to practice more gratitude. I can't imagine a better, more human approach to doing so than a short note like you've shared. Thank you and happy holidays!

**Comment by vitobotta** [comment]
Happy holidays to you too!

**Comment by IThinkImOKAY** [comment]
Thank you, devs.

**Comment by gabrielfalcao** [comment]
We need more gratitude in open-source. Kudos to @vitobotta and @compumike <3

**Comment by ssg** [comment]
I just wanted to say good luck, we're all counting on you.

**Comment by tabishiqbal** [comment]
#BeLikeVito

**Comment by yixe** [comment]
This package sucks, It has ruined my day

**Comment by PQMISSCMP** [comment]
me too, mani thank my dear friend!!
